global:
  enabled: true
  name: consul
  datacenter: aws-us-east-1
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
meshGateway:
  enabled: true
server:
  enabled: true
  replicas: 3
ui:
  enabled: true
  service:
    type: LoadBalancer
connectInject:
  enabled: true
syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  k8sAllowNamespaces: ['kube-system', 'kube-public', 'default']
  k8sDenyNamespaces: ['kube-node-lease']
dns:
  enabled: true
terminatingGateways:
  enabled: true