apiVersion: v1
kind: Pod
metadata:
  name: devwebapp
  namespace: consul
  labels:
    app: devwebapp
spec:
  selector:
    matchLabels:
      app: orgchart
  replicas: 1
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: orgchart
    spec:
      serviceAccountName: internal-app
      containers:
        - name: app
          image: burtlo/devwebapp-ruby:k8s
          env:
          - name: VAULT_ADDR
            value: "https://vault-cluster-public-vault-fcbc1a73.d087f7bf.z1.hashicorp.cloud"
          - name: VAULT_TOKEN
            value: root
  