apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: vault
  namespace: consul
  annotations:
  'consul.hashicorp.com/connect-inject': 'true'
  'consul.hashicorp.com/transparent-proxy': 'false'     
spec:
  protocol: tcp
  destination:
    addresses:
      - "vault-cluster-public-vault-fcbc1a73.d087f7bf.z1.hashicorp.cloud"
    port: 8200