apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: vault
  namespace: consul
spec:
  protocol: tcp
  destination:
    addresses:
      - "vault.com"
    port: 8200
  mode: transparent
  